(function() {var implementors = {};
implementors["syn"] = ["impl&lt;T, P&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;T&gt; for <a class=\"struct\" href=\"syn/punctuated/struct.Punctuated.html\" title=\"struct syn::punctuated::Punctuated\">Punctuated</a>&lt;T, P&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;P: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a>,&nbsp;</span>","impl&lt;T, P&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;<a class=\"enum\" href=\"syn/punctuated/enum.Pair.html\" title=\"enum syn::punctuated::Pair\">Pair</a>&lt;T, P&gt;&gt; for <a class=\"struct\" href=\"syn/punctuated/struct.Punctuated.html\" title=\"struct syn::punctuated::Punctuated\">Punctuated</a>&lt;T, P&gt;",];
implementors["xml"] = ["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;<a class=\"type\" href=\"xml/namespace/type.UriMapping.html\" title=\"type xml::namespace::UriMapping\">UriMapping</a>&lt;'a&gt;&gt; for <a class=\"struct\" href=\"xml/namespace/struct.Namespace.html\" title=\"struct xml::namespace::Namespace\">Namespace</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;<a class=\"type\" href=\"xml/namespace/type.UriMapping.html\" title=\"type xml::namespace::UriMapping\">UriMapping</a>&lt;'a&gt;&gt; for <a class=\"struct\" href=\"xml/namespace/struct.NamespaceStack.html\" title=\"struct xml::namespace::NamespaceStack\">NamespaceStack</a>","impl&lt;'a, 'b&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;<a class=\"type\" href=\"xml/namespace/type.UriMapping.html\" title=\"type xml::namespace::UriMapping\">UriMapping</a>&lt;'b&gt;&gt; for <a class=\"struct\" href=\"xml/namespace/struct.CheckedTarget.html\" title=\"struct xml::namespace::CheckedTarget\">CheckedTarget</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
